name: PrinceCensor
main: com.github.princeofmar5.PCensor
version: 1.0
author: Princeofmar5
commands:
   pc:
      description: This adds words to censor
      usage: /<command> [arg] [word]
permissions:
    princecensor.*:
        description: Gives access to all princecensor commands
        children:
            princecensor.add: true
            princecensor.remove: true
    princecensor.add:
        description: Allows you to add "swear words"
        default: op
    princecensor.remove:
        description: Allows you to remove "swear words"
        default: op