name: PCensor
main: com.github.princeofmar5.PCensor
version: 1.0.1
author: Princeofmar5
commands:
   pcensor:
      description: This adds words to censor
      usage: /<command> [arg] [word]
permissions:
    pcensor.*:
        description: Gives access to all pcensor commands
        children:
            pcensor.add: true
            pcensor.remove: true
    pcensor.add:
        description: Allows you to add "swear words"
        default: op
    pcensor.remove:
        description: Allows you to remove "swear words"
        default: op